### ISSUE TITLE
S3 upload to iDrive e2 now appears to be broken

### ISSUE THREAD

**Issue by Clumpton** [motioneye-project/motioneye#2889]
Previously saving images and video to an S3 compatible bucket on iDrive e2 worked like a charm (once you avoided spaces in the file name).

After a recent update to Debian, S3 fails, both uploads and the "Test" button. The logs show a timeout error.
The bucket and ID that I am using work just fine in S3 browser etc.

I have included the relevant portion of the log after pressing the "Test" button (just one attempt, it repeats 5 times).

Any ideas please?

boto3/botocore : 1.33.12 
Raspberry Pi4 - 
Linux motioneye 6.1.25-v8+ #1647 SMP PREEMPT Wed Apr 26 17:39:08 BST 2023 aarch64
motionEye Version | 0.43.0
Motion Version | 4.5.1
OS Version | Debian 11

```
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: testing access to s3
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: loading upload services state from "/etc/motioneye/uploadservices.json"...
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: loaded upload service "s3" for camera with id "1"
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from before-call.apigateway to before-call.api-gateway
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Loading JSON file: /usr/local/lib/python3.9/dist-packages/botocore/data/endpoints.json
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Loading JSON file: /usr/local/lib/python3.9/dist-packages/botocore/data/sdk-default-configuration.json
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fb80a39d0>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Loading JSON file: /usr/local/lib/python3.9/dist-packages/botocore/data/s3/2006-03-01/service-2.json.gz
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Loading JSON file: /usr/local/lib/python3.9/dist-packages/botocore/data/s3/2006-03-01/endpoint-rule-set-1.json.gz
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Loading JSON file: /usr/local/lib/python3.9/dist-packages/botocore/data/partitions.json
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fb8189b80>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7fb413b5e0>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fb8189940>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Setting s3 timeout as (60, 60)
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Loading JSON file: /usr/local/lib/python3.9/dist-packages/botocore/data/_retry.json
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Registering retry handlers for service: s3
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Registering S3 region redirector handler
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Registering S3Express Identity Resolver
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-parameter-build.s3.ListBuckets: calling handler <function validate_bucket_name at 0x7fb8cd85e0>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-parameter-build.s3.ListBuckets: calling handler <function remove_bucket_from_url_paths_from_model at 0x7fb8cdf430>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3RegionRedirectorv2.annotate_request_context of <botocore.utils.S3RegionRedirectorv2 object at 0x7fae6f55b0>>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-parameter-build.s3.ListBuckets: calling handler <bound method S3ExpressIdentityResolver.inject_signing_cache_key of <botocore.utils.S3ExpressIdentityResolver object at 0x7fae6f55e0>>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-parameter-build.s3.ListBuckets: calling handler <function generate_idempotent_uuid at 0x7fb8cd8430>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x7fb8cdf5e0>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirectorv2.redirect_from_cache of <botocore.utils.S3RegionRedirectorv2 object at 0x7fae6f55b0>>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Calling endpoint provider with parameters: {'Region': 'us-east-1', 'UseFIPS': False, 'UseDualStack': False, 'Endpoint': 'http://d1a7.par.idrivee2-39.com', 'ForcePathStyle': True, 'Accelerate': False, 'UseGlobalEndpoint': True, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Endpoint provider result: http://d1a7.par.idrivee2-39.com
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Selecting from endpoint provider's list of auth schemes: "sigv4". User selected auth scheme is: "None"
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Selected auth type "v4" as "v4" with signing context params: {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-call.s3.ListBuckets: calling handler <function add_expect_header at 0x7fb8cd8940>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-call.s3.ListBuckets: calling handler <bound method S3ExpressIdentityResolver.apply_signing_cache_key of <botocore.utils.S3ExpressIdentityResolver object at 0x7fae6f55e0>>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-call.s3.ListBuckets: calling handler <function add_recursion_detection_header at 0x7fb8cd80d0>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-call.s3.ListBuckets: calling handler <function inject_api_version_header_if_needed at 0x7fb8cdeca0>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Making request for OperationModel(name=ListBuckets) with params: {'url_path': '/', 'query_string': '', 'method': 'GET', 'headers': {'User-Agent': 'Boto3/1.33.12 md/Botocore#1.33.12 ua/2.0 os/linux#6.1.25-v8+ md/arch#aarch64 lang/python#3.9.2 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.33.12'}, 'body': b'', 'url': 'http://d1a7.par.idrivee2-39.com/', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7fae820580>, 'has_streaming_input': False, 'auth_type': 'v4', 's3_redirect': {'redirected': False, 'bucket': None, 'params': {}}, 'signing': {'region': 'us-east-1', 'signing_name': 's3', 'disableDoubleEncoding': True}, 'endpoint_properties': {'authSchemes': [{'disableDoubleEncoding': True, 'name': 'sigv4', 'signingName': 's3', 'signingRegion': 'us-east-1'}]}}}
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event request-created.s3.ListBuckets: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fae8205b0>>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event choose-signer.s3.ListBuckets: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7fb40f56d0>>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event choose-signer.s3.ListBuckets: calling handler <function set_operation_specific_signer at 0x7fb8cd8310>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-sign.s3.ListBuckets: calling handler <function remove_arn_from_signing_path at 0x7fb8cdf550>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event before-sign.s3.ListBuckets: calling handler <bound method S3ExpressIdentityResolver.resolve_s3express_identity of <botocore.utils.S3ExpressIdentityResolver object at 0x7fae6f55e0>>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Calculating signature using v4 auth.
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: CanonicalRequest:
Dec 12 17:34:08 motioneye meyectl[291236]: GET
Dec 12 17:34:08 motioneye meyectl[291236]: /
Dec 12 17:34:08 motioneye meyectl[291236]: host:d1a7.par.idrivee2-39.com
Dec 12 17:34:08 motioneye meyectl[291236]: x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Dec 12 17:34:08 motioneye meyectl[291236]: x-amz-date:20231212T163408Z
Dec 12 17:34:08 motioneye meyectl[291236]: host;x-amz-content-sha256;x-amz-date
Dec 12 17:34:08 motioneye meyectl[291236]: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: StringToSign:
Dec 12 17:34:08 motioneye meyectl[291236]: AWS4-HMAC-SHA256
Dec 12 17:34:08 motioneye meyectl[291236]: 20231212T163408Z
Dec 12 17:34:08 motioneye meyectl[291236]: 20231212/us-east-1/s3/aws4_request
Dec 12 17:34:08 motioneye meyectl[291236]: b3fef88bda60dfcde46dff636f4b5a54cd96c59d1b1570baaf58eb922ad3f891
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Signature:
Dec 12 17:34:08 motioneye meyectl[291236]: 2d64634ae9f6896243807274b0aa8a220f70e27e48dbd0b1dc77079b9ebeb21f
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Event request-created.s3.ListBuckets: calling handler <function add_retry_headers at 0x7fb8cdf3a0>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=http://d1a7.par.idrivee2-39.com/, headers={'User-Agent': b'Boto3/1.33.12 md/Botocore#1.33.12 ua/2.0 os/linux#6.1.25-v8+ md/arch#aarch64 lang/python#3.9.2 md/pyimpl#CPython cfg/retry-mode#legacy Botocore/1.33.12', 'X-Amz-Date': b'20231212T163408Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=xxxxxREDACTEDxxxxxx/20231212/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=xxxxxxxREDACTEDxxxxxxxxx, 'amz-sdk-invocation-id': b'b9b91eef-12e5-4022-bd59-aeb693d8f2b8', 'amz-sdk-request': b'attempt=1'}>
Dec 12 17:34:08 motioneye meyectl[291236]:    DEBUG: Starting new HTTP connection (1): d1a7.par.idrivee2-39.com:80
Dec 12 17:35:08 motioneye meyectl[291236]:    DEBUG: Exception received when sending HTTP request.
Dec 12 17:35:08 motioneye meyectl[291236]: Traceback (most recent call last):
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
Dec 12 17:35:08 motioneye meyectl[291236]:     conn = connection.create_connection(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
Dec 12 17:35:08 motioneye meyectl[291236]:     raise err
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
Dec 12 17:35:08 motioneye meyectl[291236]:     sock.connect(sa)
Dec 12 17:35:08 motioneye meyectl[291236]: socket.timeout: timed out
Dec 12 17:35:08 motioneye meyectl[291236]: During handling of the above exception, another exception occurred:
Dec 12 17:35:08 motioneye meyectl[291236]: Traceback (most recent call last):
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/httpsession.py", line 464, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     urllib_response = conn.urlopen(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
Dec 12 17:35:08 motioneye meyectl[291236]:     retries = retries.increment(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 507, in increment
Dec 12 17:35:08 motioneye meyectl[291236]:     raise six.reraise(type(error), error, _stacktrace)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
Dec 12 17:35:08 motioneye meyectl[291236]:     raise value
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
Dec 12 17:35:08 motioneye meyectl[291236]:     httplib_response = self._make_request(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
Dec 12 17:35:08 motioneye meyectl[291236]:     conn.request(method, url, **httplib_request_kw)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/awsrequest.py", line 96, in request
Dec 12 17:35:08 motioneye meyectl[291236]:     rval = super().request(method, url, body, headers, *args, **kwargs)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
Dec 12 17:35:08 motioneye meyectl[291236]:     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 1255, in request
Dec 12 17:35:08 motioneye meyectl[291236]:     self._send_request(method, url, body, headers, encode_chunked)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
Dec 12 17:35:08 motioneye meyectl[291236]:     self.endheaders(body, encode_chunked=encode_chunked)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
Dec 12 17:35:08 motioneye meyectl[291236]:     self._send_output(message_body, encode_chunked=encode_chunked)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/awsrequest.py", line 123, in _send_output
Dec 12 17:35:08 motioneye meyectl[291236]:     self.send(msg)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/awsrequest.py", line 223, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     return super().send(str)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 950, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     self.connect()
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
Dec 12 17:35:08 motioneye meyectl[291236]:     conn = self._new_conn()
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
Dec 12 17:35:08 motioneye meyectl[291236]:     raise ConnectTimeoutError(
Dec 12 17:35:08 motioneye meyectl[291236]: urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7fae6f5ee0>, 'Connection to d1a7.par.idrivee2-39.com timed out. (connect timeout=60)')
Dec 12 17:35:08 motioneye meyectl[291236]: During handling of the above exception, another exception occurred:
Dec 12 17:35:08 motioneye meyectl[291236]: Traceback (most recent call last):
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/endpoint.py", line 281, in _do_get_response
Dec 12 17:35:08 motioneye meyectl[291236]:     http_response = self._send(request)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/endpoint.py", line 377, in _send
Dec 12 17:35:08 motioneye meyectl[291236]:     return self.http_session.send(request)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/httpsession.py", line 499, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     raise ConnectTimeoutError(endpoint_url=request.url, error=e)
Dec 12 17:35:08 motioneye meyectl[291236]: botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://d1a7.par.idrivee2-39.com/"
Dec 12 17:35:08 motioneye meyectl[291236]:    DEBUG: Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x7fae6f5520>
Dec 12 17:35:08 motioneye meyectl[291236]:    DEBUG: retry needed, retryable exception caught: Connect timeout on endpoint URL: "http://d1a7.par.idrivee2-39.com/"
Dec 12 17:35:08 motioneye meyectl[291236]: Traceback (most recent call last):
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
Dec 12 17:35:08 motioneye meyectl[291236]:     conn = connection.create_connection(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
Dec 12 17:35:08 motioneye meyectl[291236]:     raise err
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
Dec 12 17:35:08 motioneye meyectl[291236]:     sock.connect(sa)
Dec 12 17:35:08 motioneye meyectl[291236]: socket.timeout: timed out
Dec 12 17:35:08 motioneye meyectl[291236]: During handling of the above exception, another exception occurred:
Dec 12 17:35:08 motioneye meyectl[291236]: Traceback (most recent call last):
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/httpsession.py", line 464, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     urllib_response = conn.urlopen(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
Dec 12 17:35:08 motioneye meyectl[291236]:     retries = retries.increment(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 507, in increment
Dec 12 17:35:08 motioneye meyectl[291236]:     raise six.reraise(type(error), error, _stacktrace)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/six.py", line 719, in reraise
Dec 12 17:35:08 motioneye meyectl[291236]:     raise value
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
Dec 12 17:35:08 motioneye meyectl[291236]:     httplib_response = self._make_request(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
Dec 12 17:35:08 motioneye meyectl[291236]:     conn.request(method, url, **httplib_request_kw)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/awsrequest.py", line 96, in request
Dec 12 17:35:08 motioneye meyectl[291236]:     rval = super().request(method, url, body, headers, *args, **kwargs)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
Dec 12 17:35:08 motioneye meyectl[291236]:     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 1255, in request
Dec 12 17:35:08 motioneye meyectl[291236]:     self._send_request(method, url, body, headers, encode_chunked)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
Dec 12 17:35:08 motioneye meyectl[291236]:     self.endheaders(body, encode_chunked=encode_chunked)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
Dec 12 17:35:08 motioneye meyectl[291236]:     self._send_output(message_body, encode_chunked=encode_chunked)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/awsrequest.py", line 123, in _send_output
Dec 12 17:35:08 motioneye meyectl[291236]:     self.send(msg)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/awsrequest.py", line 223, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     return super().send(str)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3.9/http/client.py", line 950, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     self.connect()
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
Dec 12 17:35:08 motioneye meyectl[291236]:     conn = self._new_conn()
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 174, in _new_conn
Dec 12 17:35:08 motioneye meyectl[291236]:     raise ConnectTimeoutError(
Dec 12 17:35:08 motioneye meyectl[291236]: urllib3.exceptions.ConnectTimeoutError: (<botocore.awsrequest.AWSHTTPConnection object at 0x7fae6f5ee0>, 'Connection to d1a7.par.idrivee2-39.com timed out. (connect timeout=60)')
Dec 12 17:35:08 motioneye meyectl[291236]: During handling of the above exception, another exception occurred:
Dec 12 17:35:08 motioneye meyectl[291236]: Traceback (most recent call last):
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/retryhandler.py", line 307, in _should_retry
Dec 12 17:35:08 motioneye meyectl[291236]:     return self._checker(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/retryhandler.py", line 363, in __call__
Dec 12 17:35:08 motioneye meyectl[291236]:     checker_response = checker(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/retryhandler.py", line 247, in __call__
Dec 12 17:35:08 motioneye meyectl[291236]:     return self._check_caught_exception(
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
Dec 12 17:35:08 motioneye meyectl[291236]:     raise caught_exception
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/endpoint.py", line 281, in _do_get_response
Dec 12 17:35:08 motioneye meyectl[291236]:     http_response = self._send(request)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/endpoint.py", line 377, in _send
Dec 12 17:35:08 motioneye meyectl[291236]:     return self.http_session.send(request)
Dec 12 17:35:08 motioneye meyectl[291236]:   File "/usr/local/lib/python3.9/dist-packages/botocore/httpsession.py", line 499, in send
Dec 12 17:35:08 motioneye meyectl[291236]:     raise ConnectTimeoutError(endpoint_url=request.url, error=e)
Dec 12 17:35:08 motioneye meyectl[291236]: botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: "http://d1a7.par.idrivee2-39.com/"
Dec 12 17:35:08 motioneye meyectl[291236]:    DEBUG: Retry needed, action of: 0.8076633488937912
Dec 12 17:35:08 motioneye meyectl[291236]:    DEBUG: Event needs-retry.s3.ListBuckets: calling handler <bound method S3RegionRedirectorv2.redirect_from_error of <botocore.utils.S3RegionRedirectorv2 object at 0x7fae6f55b0>>
Dec 12 17:35:08 motioneye meyectl[291236]:    DEBUG: Response received to retry, sleeping for 0.8076633488937912 seconds
```

**Comment by MichaIng** [comment]
If the issue still persists, can you retry with latest motionEye?

The error seems to coming from boto3 itself, and its API did not change. The initial error is a timeout, hence could have been a temporary network issue, or a bug in boto3 that was resolved in the meantime.
