### ISSUE TITLE
ME broken after upgrade to Debian 12

### ISSUE THREAD

**Issue by speeskeek** [motioneye-project/motioneye#2909]
hi all

a few years runnign ME with very much plesure. I guess since 1,5-2y now running the pyton3 version. all went well..

today I upgraded my nas-system (taht acts also als motioneye system) to debian12. now i cant start anymore :(

× motioneye.service - motionEye Server
     Loaded: loaded (/etc/systemd/system/motioneye.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-01-04 20:31:05 CET; 5s ago
   Duration: 43ms
    Process: 90895 ExecStart=/usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf (code=exited, status=1/FAILURE)
   Main PID: 90895 (code=exited, status=1/FAILURE)
        CPU: 40ms

Jan 04 20:31:05 Z800 systemd[1]: Started motioneye.service - motionEye Server.
Jan 04 20:31:05 Z800 meyectl[90895]: Traceback (most recent call last):
Jan 04 20:31:05 Z800 meyectl[90895]:   File "/usr/local/bin/meyectl", line 5, in <module>
Jan 04 20:31:05 Z800 meyectl[90895]:     from motioneye.meyectl import main
Jan 04 20:31:05 Z800 meyectl[90895]: ModuleNotFoundError: No module named 'motioneye'
Jan 04 20:31:05 Z800 systemd[1]: motioneye.service: Main process exited, code=exited, status=1/FAILURE
Jan 04 20:31:05 Z800 systemd[1]: motioneye.service: Failed with result 'exit-code'.

**Comment by speeskeek** [comment]
same if I run directly meyectl

root@Z800:/var/www# meyectl 
Traceback (most recent call last):
  File "/usr/local/bin/meyectl", line 5, in <module>
    from motioneye.meyectl import main
ModuleNotFoundError: No module named 'motioneye'




I did a re-install following the dev-wiki for installing the python3 version

**Comment by speeskeek** [comment]
root@Z800:/var/www# motioneye_init 
Traceback (most recent call last):
  File "/usr/local/bin/motioneye_init", line 5, in <module>
    from motioneye.motioneye_init import main
ModuleNotFoundError: No module named 'motioneye'

**Comment by speeskeek** [comment]
And if I run it as a normal user (bart@ … )

bart@Z800:~$ meyectl 
usage: meyectl [command] [-c CONFIG_FILE] [-d] [-h] [-l] [-v] [command options...]

available commands:
  startserver
  stopserver
  sendmail
  sendtelegram
  webhook
  shell

**Comment by speeskeek** [comment]
Solved

installed it as user not as root 🙄
